### ISSUE TITLE
Plugin does not support non-standard url layouts

### ISSUE THREAD

**Issue by Mofman1** [anth0d/chrome-confluence-search#1]
The company I work for has our confluence on a nonstandard domain that doesn't include the /wiki  part of the domain after the url. A sample url from our confluence is https://confluence.****.com/display/HD/PIOP or https://confluence.****.com/pages/viewpage.action?pageId=10584884

Currently this does not work with this extension because of this.

**Comment by anth0d** [comment]
Hey sorry about that. Thanks for opening this. (I didn't receive any kind of notification from Github so that's why I am responding so late.) 

I will update this once I get to address your issue.

**Comment by anth0d** [comment]
This will be addressed in version `1.1.0` which is currently in review in the Chrome Web Store... I will keep this open until it's actually published.

**Comment by anth0d** [comment]
Hello @Mofman1 ! Just wanted to let you know that the fix for this issue has been released with version `1.1.0`. 

If you have the extension installed already, update it [here](chrome://extensions/)

Or, you can [install the extension here](https://chrome.google.com/webstore/detail/confluence-quick-search/gimcmmlpmjffkpbomagapjhdfbbeldfk).

Thanks again for reporting this issue. Hope you find the tool useful.
